name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  # Validación de mensajes de commit
  validate-commit:
    name: Validate Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci # npm ci es más rápido y confiable para entornos de CI/CD

      - name: Validate commit messages
        run: |
          last_commit_message=$(git log -1 --pretty=format:%s)
          if [[ ! "$last_commit_message" =~ ^(fix:|feat:) ]]; then
            echo "Error: The commit message does not follow the required format (fix: or feat:)"
            exit 1
          fi

  # Ejecución de migraciones
  run-migrations:
    name: Run Database Migrations
    runs-on: ubuntu-latest
    needs: validate-commit
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Run migrations
        run: npm run migration:tenants:run

  # Construcción de la aplicación
  build-app:
    name: Build Application
    runs-on: ubuntu-latest
    needs: run-migrations
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build
        env:
          NODE_ENV: production # Configuración del entorno de compilación

  # Despliegue en servidor
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: build-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Deploy to Server
        run: |
          # Implementa tu script de despliegue aquí
          # Ejemplo: ssh user@server "cd /path/to/app && git pull && npm install && npm run start"
          echo "Implement deployment script here"
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }} # Llave SSH para conexión al servidor
